http:
  port: 8001
admin:
  port: 9876
  host: localhost
apiEndpoints:
  auth-api:
    host: localhost
    paths: '/user/*'
  order-api:
    host: localhost
    paths: '/pizza/*'
  build-api:
    host: localhost
    paths: '/build/*'
  cart-api:
    host: localhost
    paths: '/cart/*'
serviceEndpoints:
  auth-service:
    url: 'http://localhost:5001/'
  order-service:
    url: 'http://localhost:5002/'
  build-service:
    url: 'http://localhost:5003/'
  cart-service:
    url: 'http://localhost:5004/'
policies:
  - proxy
pipelines:
  default:
    apiEndpoints:
      - auth-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: auth-service 
              changeOrigin: true
  
  order-pizza:
    apiEndpoints:
      - order-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: order-service 
              changeOrigin: true
  
  build-pizza:
    apiEndpoints:
      - build-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: build-service 
              changeOrigin: true
  
  cart:
    apiEndpoints:
      - cart-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: cart-service 
              changeOrigin: true